var age = 30;
var price = 300;
var sum = age + price;
console.log(sum);
var fn = "keshireddy";
var ln = "sushanth";
var fuln = fn + " " + ln;
console.log(fuln);
var isstudent = true;
var isAdult = age >= 18;
console.log("Is Student:", isstudent);
console.log("Is Adult:", isAdult);
var pn;
var city;
console.log("Phone Number:", pn);
console.log("City:", city);
